%%%
  VERSION:1
  LANGUAGE:ENGLISH
%%%
MODULE MOD_Main

    ! -------------------------------
    ! Define customized variables here
    ! ...

	! Tool variables: 
	PERS tooldata Spindle := [TRUE, [[32.000,-
		0.000,260.000],[0.94264,0.00000,0.33381,0.00000]],[5,[16.000,0.0
		00,130.000],[1,0,0,0],0,0,0]];

	! Reference variables:
	PERS wobjdata Worktable := [False, True, "", [[200.000, 480.000,
		100.000], [1.00000, 0.00000, 0.00000, 0.00000]],[[0.000000,
		0.000000, 0.000000], [1.000000, 0.000000, 0.000000, 0.000000]]];

	PROC Prog1()
		ConfJ \On;
		ConfL \Off;
		MoveL [[290.892,-480.000,255.104],[0.00872654,-0.00000000,0.99996192,0.00000000],[0,0,-1,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=wobj0;
		v10,z1,Spindle \WObj:=Worktable;
		MoveL [[152.863,-532.172,100.050],[0.00872654,-0.00000000,0.99996192,0.00000000],[-1,0,-1,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=wobj0;
		v10,z1,Spindle \WObj:=Worktable;
		MoveL [[150.000,-430.000,100.000],[0.00872654,-0.00000000,0.99996192,-0.00000000],[0,-1,0,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=wobj0;
		v10,z1,Spindle \WObj:=Worktable;
		MoveL [[250.000,-430.000,100.000],[0.00872654,-0.00000000,0.99996192,-0.00000000],[0,-1,0,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=wobj0;
		v10,z1,Spindle \WObj:=Worktable;
		MoveL [[250.000,-530.000,100.000],[0.00872654,-0.00000000,0.99996192,-0.00000000],[-1,0,-1,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=wobj0;
		v10,z1,Spindle \WObj:=Worktable;
		MoveL [[290.892,-209.370,255.104],[0.00872654,-0.00000000,0.99996192,-0.00000000],[0,-1,0,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=wobj0;
		v10,z1,Spindle \WObj:=Worktable;
	ENDPROC

	PROC Main()
		ConfJ \On;
		ConfL \Off;
		! Program generated by RoboDK v5.3.4 for ABB IRB 120-3/0.6 on 17/01/2022 12:53:36
		! Using nominal kinematics.
		Prog1;
	ENDPROC

ENDMODULE
